version: "3.8"
services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    image: techbranch/frontend
    ports:
      - 3000:3000
    volumes:
      - ./:/usr/src/app
    command: npm start
